package allyouneed.gt

import allyouneed.async.AsyncBlockKind
import allyouneed.async.AsyncStructureEntityBlock
import allyouneed.async.IAsyncKindBlock
import com.gregtechceu.gtceu.api.block.MetaMachineBlock
import com.gregtechceu.gtceu.api.machine.MachineDefinition
import net.minecraft.core.BlockPos
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.entity.BlockEntity
import net.minecraft.world.level.block.state.BlockBehaviour
import net.minecraft.world.level.block.state.BlockState
import net.minecraft.world.level.block.state.StateDefinition

/**
 * GT machine block of the async synthesis system (the three controllers and the three connectors).
 * Wraps a regular [MetaMachineBlock] and exposes the async block kind so the common structure
 * detectors read controllers/connectors from the world regardless of which registration path
 * produced them.
 *
 * Two concrete flavours mirror the vanilla async blocks so the static blockstates generated by
 * `common/resgen` resolve for both the AE and the GT registration paths:
 *  - [AsyncStructureGtMachineBlock] (controllers): `facing` + `formed`
 *  - [AsyncStructureGtConnectorBlock] (connectors): `facing` + `formed` + `powered`
 *
 * The connector-ness must be baked into a concrete subclass rather than a derived instance field:
 * `createBlockStateDefinition` is invoked from the `BlockBehaviour` constructor chain, before any
 * field of this class is initialized, so a `connector = kind.role == ...` field would read as
 * `false` at that point and silently drop POWERED from the state definition (GTCEu itself avoids
 * this trap by reading the static `MachineDefinition.getBuilt()`).
 */
open class AsyncStructureGtMachineBlock(
    props: Properties,
    definition: MachineDefinition,
    override val kind: AsyncBlockKind,
) : MetaMachineBlock(props, definition), IAsyncKindBlock {

    init {
        registerDefaultState(defaultBlockState().setValue(AsyncStructureEntityBlock.FORMED, false))
    }

    override fun createBlockStateDefinition(builder: StateDefinition.Builder<Block, BlockState>) {
        super.createBlockStateDefinition(builder)
        builder.add(AsyncStructureEntityBlock.FORMED)
    }

    override fun newBlockEntity(pos: BlockPos, state: BlockState): BlockEntity? =
        definition.blockEntityType.create(pos, state)
}

/** GT machine block of the async connectors: additionally carries the [POWERED] state. */
class AsyncStructureGtConnectorBlock(
    props: Properties,
    definition: MachineDefinition,
    kind: AsyncBlockKind,
) : AsyncStructureGtMachineBlock(props, definition, kind) {

    init {
        registerDefaultState(defaultBlockState().setValue(AsyncStructureEntityBlock.POWERED, false))
    }

    override fun createBlockStateDefinition(builder: StateDefinition.Builder<Block, BlockState>) {
        super.createBlockStateDefinition(builder)
        builder.add(AsyncStructureEntityBlock.POWERED)
    }
}
