package allyouneed.resgen

/**
 * 分子装配室用的机器物品标签内容（resgen 生成）。
 *
 * 可选条目使用 `"required": false`，缺失模组不会导致标签加载失败。
 * GT 单方块机器按电压阶：`{tier}_electric_furnace` 等。
 *
 * Machine-item tag contents for the machine assembler (generated by resgen).
 * Optional entries use `"required": false` so missing mods never break tag load.
 * GT simple machines are tiered: `{tier}_electric_furnace`, etc.
 */

// GTCEu 单方块机器电压前缀
private val GT_TIERS = listOf(
    "lv", "mv", "hv", "ev", "iv", "luv", "zpm", "uv",
    "uhv", "uev", "uiv", "uxv", "opv",
)

private fun gtTiered(name: String): List<String> =
    GT_TIERS.map { "gtceu:${it}_$name" }

private fun gtSteam(name: String): List<String> = listOf(
    "gtceu:lp_steam_$name",
    "gtceu:hp_steam_$name",
)

/**
 * 在 [AssetGen] 中写入机器物品标签。
 * Apply machine item tags inside an [AssetGen] block.
 */
fun AssetGen.machineItemTags() {
    // --- 合成 minecraft:crafting ---
    itemTag(
        path = "machines/crafting",
        required = listOf(
            "minecraft:crafting_table",
        ),
        optional = listOf(
            "minecraft:crafter",
            "ae2:crafting_terminal",
            "ae2:wireless_crafting_terminal",
            "mekanism:formulaic_assemblicator",
        ),
    )

    // --- 熔炼 minecraft:smelting ---
    // GT 蒸汽/电炉 + Mek 充能冶炼炉作为熔炉类机器
    itemTag(
        path = "machines/smelting",
        required = listOf(
            "minecraft:furnace",
        ),
        optional = buildList {
            addAll(gtSteam("furnace"))
            addAll(gtTiered("electric_furnace"))
            add("mekanism:energized_smelter")
        },
    )

    // --- 高炉 minecraft:blasting ---
    itemTag(
        path = "machines/blasting",
        required = listOf(
            "minecraft:blast_furnace",
        ),
        optional = buildList {
            // GT EBF 配方体系不同，仅作「高炉类」主机可选身份
            add("gtceu:electric_blast_furnace")
            add("gtceu:mega_blast_furnace")
            add("gtceu:primitive_blast_furnace")
        },
    )

    // --- 烟熏 minecraft:smoking ---
    itemTag(
        path = "machines/smoking",
        required = listOf(
            "minecraft:smoker",
        ),
        optional = emptyList(),
    )
}
