-allowaccessmodification
-dontwarn **
-dontnote **
-keepattributes Signature,InnerClasses,EnclosingMethod
-keep,allowoptimization class appeng.api.stacks.** { *; }
-keep,allowoptimization class net.minecraft.resources.** { *; }
